# Generated by Django 3.2 on 2021-12-30 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '게시글 사진', 'verbose_name_plural': '게시글 사진'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_at'], 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='posts/%Y/%m/%d', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='해당 게시글'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(verbose_name='글 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Tag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name='글 제목'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, verbose_name='태그명'),
        ),
    ]
