# Generated by Django 3.2 on 2021-12-30 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20211230_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_set',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
    ]
