# Generated by Django 3.2 on 2022-01-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_like_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_photos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.photo'),
            preserve_default=False,
        ),
    ]
