# Generated by Django 3.2 on 2022-01-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_photo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_photos',
        ),
    ]
