# Generated by Django 3.2 on 2022-01-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_photo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
    ]
