# Generated by Django 3.2 on 2022-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220109_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts/&Y/%m/%d', verbose_name='게시글 사진'),
        ),
    ]
