# Generated by Django 3.2 on 2022-01-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
