# Generated by Django 3.2 on 2022-01-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.photo'),
            preserve_default=False,
        ),
    ]
